#!/usr/bin/env bash
# pr-watchdog — local replacement for GitHub Actions while billing is exhausted.
#
# Polls open PRs every WATCHDOG_INTERVAL seconds. For each PR whose head SHA
# changed since the last tick, the daemon:
#   1. Checks out the head SHA into an isolated git worktree.
#   2. Runs scripts/ci-local.sh (the same 5-step gate humans run pre-PR).
#   3. If green, asks Claude Code to /code-review the diff.
#   4. Posts a verdict comment on the PR via `gh`.
#
# Cost guard: step 3 only runs when step 2 passes. A red CI mirror posts the
# failure log and skips the model call.
#
# Subcommands:
#   start | stop | status | tick | run | review <pr> | help
#
# Env:
#   WATCHDOG_INTERVAL    seconds between ticks (default 900)
#   WATCHDOG_REPO        owner/repo (default: auto from `gh`)
#   WATCHDOG_AUTOAPPROVE if "1", `gh pr review --approve` on green
#   WATCHDOG_SKIP_BOTS   if "1" (default), skip *[bot] / app/* authors
#   WATCHDOG_CLAUDE_BIN  path to claude CLI (default: claude on PATH)

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="$REPO_ROOT/.claude/watchdog"
PID_FILE="$STATE_DIR/pid"
LOG_FILE="$STATE_DIR/watchdog.log"
RUNS_DIR="$STATE_DIR/runs"
WT_DIR="$STATE_DIR/worktrees"

INTERVAL="${WATCHDOG_INTERVAL:-900}"
AUTOAPPROVE="${WATCHDOG_AUTOAPPROVE:-0}"
SKIP_BOTS="${WATCHDOG_SKIP_BOTS:-1}"
CLAUDE_BIN="${WATCHDOG_CLAUDE_BIN:-claude}"

mkdir -p "$STATE_DIR" "$RUNS_DIR" "$WT_DIR"

log() { printf '[%s] %s\n' "$(date -Iseconds)" "$*" | tee -a "$LOG_FILE"; }
err() { log "ERROR: $*" >&2; }
need() { command -v "$1" >/dev/null 2>&1 || { err "missing dep: $1"; exit 127; }; }

detect_repo() {
    if [ -n "${WATCHDOG_REPO:-}" ]; then
        echo "$WATCHDOG_REPO"; return
    fi
    gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null
}

review_pr() {
    local pr_number="$1"
    local head_sha="$2"
    local short_sha="${head_sha:0:7}"
    local run_log="$RUNS_DIR/pr-$pr_number-$short_sha.log"
    local wt="$WT_DIR/pr-$pr_number"

    log "PR #$pr_number → reviewing $short_sha"

    rm -rf "$wt"
    git -C "$REPO_ROOT" fetch origin "pull/$pr_number/head" 2>>"$LOG_FILE" || true
    if ! git -C "$REPO_ROOT" worktree add --force --detach "$wt" FETCH_HEAD 2>>"$LOG_FILE"; then
        err "PR #$pr_number → worktree add failed"
        return 1
    fi

    local ci_ok=0
    (cd "$wt" && bash "$REPO_ROOT/scripts/ci-local.sh") > "$run_log" 2>&1 || ci_ok=1

    if [ "$ci_ok" -eq 0 ]; then
        log "PR #$pr_number → ci-local PASS"
        post_green "$pr_number" "$short_sha" "$run_log" "$wt"
    else
        log "PR #$pr_number → ci-local FAIL"
        post_red "$pr_number" "$short_sha" "$run_log"
    fi

    git -C "$REPO_ROOT" worktree remove --force "$wt" 2>>"$LOG_FILE" || true
}

post_green() {
    local pr_number="$1" sha="$2" run_log="$3" wt="$4"
    local review_md="$RUNS_DIR/pr-$pr_number-$sha.review.md"

    if command -v "$CLAUDE_BIN" >/dev/null 2>&1; then
        log "PR #$pr_number → invoking $CLAUDE_BIN -p /code-review"
        (cd "$wt" && "$CLAUDE_BIN" -p "/code-review" --output-format text) \
            > "$review_md" 2>>"$LOG_FILE" || \
            echo "_(code-review failed; see $LOG_FILE)_" > "$review_md"
    else
        echo "_(claude CLI not on PATH — set WATCHDOG_CLAUDE_BIN)_" > "$review_md"
    fi

    local body
    body=$(cat <<EOF
✅ **Local CI mirror green** for \`$sha\` — posted by pr-watchdog.

CI billing is exhausted this cycle; the five gates from \`ci.yml\` + \`security.yml\` were run locally instead:

\`\`\`
$(tail -25 "$run_log")
\`\`\`

### \`/code-review\` verdict

$(cat "$review_md")

---
<sub>Generated by [\`scripts/pr-watchdog.sh\`](../blob/main/scripts/pr-watchdog.sh). To re-run: \`make watchdog-tick\`.</sub>
EOF
)
    gh pr comment "$pr_number" --body "$body" >>"$LOG_FILE" 2>&1 || \
        err "PR #$pr_number → comment post failed"

    if [ "$AUTOAPPROVE" = "1" ]; then
        gh pr review "$pr_number" --approve --body \
            "Approved by local pr-watchdog (CI mirror + /code-review both green)." \
            >>"$LOG_FILE" 2>&1 || err "PR #$pr_number → auto-approve failed"
    fi
}

post_red() {
    local pr_number="$1" sha="$2" run_log="$3"
    local body
    body=$(cat <<EOF
❌ **Local CI mirror failed** for \`$sha\` — posted by pr-watchdog.

CI billing is exhausted this cycle. Local gate output (last 40 lines):

\`\`\`
$(tail -40 "$run_log")
\`\`\`

Skipped \`/code-review\` to save tokens until ci-local is green.

---
<sub>Generated by [\`scripts/pr-watchdog.sh\`](../blob/main/scripts/pr-watchdog.sh). Re-run with \`make watchdog-tick\` after pushing a fix.</sub>
EOF
)
    gh pr comment "$pr_number" --body "$body" >>"$LOG_FILE" 2>&1 || \
        err "PR #$pr_number → comment post failed"
}

tick() {
    local repo
    repo="$(detect_repo)"
    [ -z "$repo" ] && { err "no repo (gh not configured? set WATCHDOG_REPO)"; return 1; }

    log "tick start — repo=$repo skip_bots=$SKIP_BOTS"

    local rows
    rows=$(gh pr list -R "$repo" --state open \
            --json number,headRefOid,isDraft,author \
            --jq '.[] | [.number, .headRefOid, (.isDraft|tostring), .author.login] | @tsv' \
            2>>"$LOG_FILE") || { err "gh pr list failed"; return 1; }

    local pr_number head_sha is_draft author
    while IFS=$'\t' read -r pr_number head_sha is_draft author; do
        [ -z "$pr_number" ] && continue
        if [ "$is_draft" = "true" ]; then
            log "PR #$pr_number → skipping (draft)"; continue
        fi
        if [ "$SKIP_BOTS" = "1" ] && [[ "$author" == *"[bot]" || "$author" == "app/"* ]]; then
            log "PR #$pr_number → skipping (bot: $author)"; continue
        fi
        local marker="$STATE_DIR/seen-$pr_number.sha"
        local last=""
        [ -f "$marker" ] && last="$(cat "$marker")"
        if [ "$head_sha" = "$last" ]; then
            continue
        fi
        if review_pr "$pr_number" "$head_sha"; then
            echo "$head_sha" > "$marker"
        fi
    done <<< "$rows"

    log "tick done"
}

run_loop() {
    log "watchdog loop start — interval=${INTERVAL}s"
    trap 'log "received signal, exiting"; exit 0' INT TERM
    while true; do
        tick || err "tick failed"
        sleep "$INTERVAL"
    done
}

start_daemon() {
    if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        echo "already running (pid $(cat "$PID_FILE"))" >&2; return 1
    fi
    nohup bash "$0" run >>"$LOG_FILE" 2>&1 &
    echo $! > "$PID_FILE"
    echo "started (pid $!, interval=${INTERVAL}s, log=$LOG_FILE)"
}

stop_daemon() {
    if [ ! -f "$PID_FILE" ]; then echo "not running" >&2; return 1; fi
    local pid; pid="$(cat "$PID_FILE")"
    if kill "$pid" 2>/dev/null; then echo "stopped (pid $pid)"
    else echo "process $pid not found; removing stale pid file" >&2; fi
    rm -f "$PID_FILE"
}

status_daemon() {
    if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        echo "running (pid $(cat "$PID_FILE"))"
    else
        echo "not running"
    fi
    echo "seen ledger:"
    for f in "$STATE_DIR"/seen-*.sha; do
        [ -f "$f" ] || continue
        printf '  %s → %s\n' "$(basename "$f" .sha | sed s/seen-/PR\ #/)" "$(cat "$f")"
    done
    echo "tail of $LOG_FILE:"
    tail -10 "$LOG_FILE" 2>/dev/null | sed 's/^/  /'
}

review_one() {
    local pr_number="$1"
    [ -z "$pr_number" ] && { err "usage: pr-watchdog.sh review <pr>"; return 2; }
    local sha
    sha="$(gh pr view "$pr_number" --json headRefOid --jq .headRefOid)" || {
        err "PR #$pr_number not found"; return 1
    }
    review_pr "$pr_number" "$sha" && echo "$sha" > "$STATE_DIR/seen-$pr_number.sha"
}

need gh
need git

case "${1:-help}" in
    start)   start_daemon ;;
    stop)    stop_daemon ;;
    status)  status_daemon ;;
    tick)    tick ;;
    run)     run_loop ;;
    review)  shift; review_one "${1:-}" ;;
    help|-h|--help)
        sed -n '2,/^set -uo/p' "$0" | sed '$d' | sed 's/^# \?//'
        ;;
    *)       echo "usage: $0 {start|stop|status|tick|run|review <pr>}" >&2; exit 2 ;;
esac
